### ISSUE TITLE
Invitation of thelinuxfoundation to GitHub CDEvents org

### ISSUE THREAD

**Issue by fdegir** [cdevents/community#16]
In order for CD Foundation to support the project properly and make insights available for the project on LFX, the user thelinuxfoundation must be invited to the GitHub CDEvents Organization.

Please invite the user thelinuxfoundation as an owner at the organization level (not per repository) to the GitHub organization.

**Comment by afrittoli** [comment]
I invited @thelinuxfoundation to the org as owner

**Comment by afrittoli** [comment]
The invite has been accepted
