### ISSUE TITLE
CDEvents Most Valuable Contributor Award 2024

### ISSUE THREAD

**Issue by e-backmark-ericsson** [cdevents/community#43]
This issue is to receive nominations for the CDEvents Most Valuable Contributor (MVC) Award 2024 for CDF.

This award recognizes excellence of contributions to the CDEvents project, which may be any or a combination of contributions to the specification, work on the SDKs, implementation of proofs of concepts, advocacy and fostering adoption in other communities.

To nominate someone, reply to this issue with the following:

- Full name of the person you’re nominating
- Short description of their contributions to the CDEvents project and why they should win.

**Nomination deadline**: Sunday, February 19, 2024 at 11:59 PST
**Please note**: Last year's winner, Emil Bäckmark, cannot win the award for CDEvents MVC again this year.

[CDF Project Awards Guidelines](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md#project-awards)

[Other CDF Community Awards for 2024](https://cd.foundation/cdf-community-awards-2024/)

**Comment by e-backmark-ericsson** [comment]
I would like to nominate Andrea Frittoli (@afrittoli) for the CDEvents MVC award this year

Andrea is an active contributor to most CDEvents repos, both by posting new issues and PRs and also by commenting and reviewing other's requests. Andrea is also a driver of the CDEvents workgroup meeting and has shown great dedication to the project.

**Comment by afrittoli** [comment]
I would like to nominate Ben Powell (@xibz) for the CDEvents MVC award this year.

Ben has been contributing consistently for more than a year to the CDEvents project, driving the specification and implementation of several important features as well as relentlessly advocating for the project. Thank you Ben for your great work!
