### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by afrittoli** [cdevents/community#44]
- [x] Make sure all issues are resolved: https://github.com/cdevents/spec/milestone/4
- [x] Switch all versions from 0.4.0-draft to 0.4.0 https://github.com/cdevents/spec/pull/199
- [x] Switch all event versions from version-draft to version https://github.com/cdevents/spec/pull/199
- [x] Remove mentions of draft / work-in-progress content https://github.com/cdevents/spec/pull/199
- [x] Update the README to mention 0.4.0 as latest release https://github.com/cdevents/spec/pull/201
- [x] Tag spec and create branch for patch releases https://github.com/cdevents/spec/releases/tag/v0.4.0
- [x] Produce release notes through GitHub https://github.com/cdevents/spec/releases/tag/v0.4.0
- [x] Update cdevents.dev as needed https://github.com/cdevents/cdevents.dev/pull/42
- [x] Prepare a release announcement for v0.4 (see #47 for reference) - [draft](https://docs.google.com/document/d/1vmwMnW1gb4njGzFTv8BDZe-MO8lbg5-MKcMdfu4oMGk/edit#heading=h.q2md51f8azih)
- [ ] Announce release on slack and mailing list
- [x] Move `main` in the spec repo to the new -draft release https://github.com/cdevents/spec/pull/203
- [ ] Updates the SDKs
   - [x] Golang
   - [x] Java
   - [x] Rust
   - [ ] Python

**Comment by e-backmark-ericsson** [comment]
Should we also create issues as part of this issue, for each tool that implements CDEvents support, to upgrade to this new version? Those issues should then be added to our [CDEvents in tools](https://github.com/orgs/cdevents/projects/4) project

**Comment by afrittoli** [comment]
The Python SDK is currently un-maintained. Closing this issue.

**Comment by afrittoli** [comment]
> Should we also create issues as part of this issue, for each tool that implements CDEvents support, to upgrade to this new version? Those issues should then be added to our [CDEvents in tools](https://github.com/orgs/cdevents/projects/4) project

We can track that, but I wouldn't block this issue on that.
